version: '3.8'

services:
  php-server:
    build: .
    container_name: php-otel-server
    volumes:
      - ${PROJECT_PATH}:/var/www/html/
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./conf/opentelemetry.ini:/usr/local/etc/php/conf.d/opentelemetry.ini:ro
      - ./conf/pgsql.ini:/usr/local/etc/php/conf.d/pgsql.ini:ro
    ports:
      - "${PHP_SERVER_PORT:-8080}:8080"
    command: "php -S 0.0.0.0:8080"
    networks:
      - php-op-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:${PSQL_PORT:-5432}"
    networks:
      - php-op-network
  jaeger:
    image: jaegertracing/jaeger:2.7.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"   # gRPC (OTLP) port
      - "4318:4318"   # HTTP (OTLP) port
    networks:
      - php-op-network
networks:
  php-op-network:
    driver: bridge

