version: 1.0
name: 'Caop'
entities:
  - class: "CaOp\\Template\\TelemetryTemplates"
    method: "handleRequest"
    span_name: 'RequestInfo 😎'
    include: 
      - file: "curl_telemetry_config.yml"
      - file: "postgres_telemetry_config.yml"
